2025-04-02 20:58:32,879 - INFO - || Project succesfully created
2025-04-02 20:58:32,879 - INFO - || BAGHandler succesfully created.

2025-04-02 20:58:33,096 - INFO - || ............FETCHING TILE IDS............
    ----> 8/504/584
    ----> 8/504/592
    ----> 9/512/584
    ----> 9/512/588
    ----> 9/516/584
    ----> 9/516/588
    ----> 9/512/592
    ----> 9/516/592
2025-04-02 20:58:33,212 - INFO - || ............FETCHING TILE IDS SUCCESFULL 8............

2025-04-02 20:58:33,212 - INFO - || ............DOWNLOADING TILES FROM BAG SERVICE............
2025-04-02 20:58:34,385 - ERROR - || An error occurred during downloading of BAG tiles: Traceback (most recent call last):
  File "e:\Projects\Coding\git-automatic-bag3d-data-downloader\Python\models\3dbag_model.py", line 98, in download_bag_tiles
    self.currentProject.logger.log_message("info","    ----> " + tile + "(" + len(tile['CityObjects'] + ")", True, True, False))
                                                                                  ~~~~^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

